#!/bin/bash
# One-shot interactive setup for deploying a Mimir project.
# Creates .mimir-deploy.env and .mimir-deploy.secrets with all required config.
# Usage: mimir deploy setup
source "$(dirname "$0")/common.sh"

echo "=== Mimir Deploy Setup ==="
echo "Project: ${PROJECT} (${MIMIR_PROJ_DIR})"
echo ""

ENV_FILE="${MIMIR_PROJ_DIR}/.mimir-deploy.env"
SECRETS_FILE="${MIMIR_PROJ_DIR}/.mimir-deploy.secrets"

# Check if already configured
if [ -f "${ENV_FILE}" ] && [ -f "${SECRETS_FILE}" ]; then
    echo "Deploy config already exists:"
    echo "  ${ENV_FILE}"
    echo "  ${SECRETS_FILE}"
    read -p "Overwrite? [y/N] " -r
    [[ ! "${REPLY}" =~ ^[Yy]$ ]] && { echo "Aborted."; exit 0; }
    echo ""
fi

# --- DEPLOY_PATH ---
echo "DEPLOY_PATH: Directory containing server binaries and database backups."
echo "  Expected layout:"
echo "    <path>/Account/Account.exe"
echo "    <path>/Login/Login.exe"
echo "    <path>/Databases/*.bak"
echo ""

if [ -n "${DEPLOY_PATH:-}" ]; then
    echo "  Current: ${DEPLOY_PATH}"
    read -p "  DEPLOY_PATH [${DEPLOY_PATH}]: " input_deploy_path
    DEPLOY_PATH="${input_deploy_path:-${DEPLOY_PATH}}"
else
    read -p "  DEPLOY_PATH: " DEPLOY_PATH
fi

if [ -z "${DEPLOY_PATH}" ]; then
    echo "ERROR: DEPLOY_PATH is required."
    exit 1
fi

if [ ! -d "${DEPLOY_PATH}" ]; then
    echo "WARNING: ${DEPLOY_PATH} does not exist yet. Create it and populate before starting containers."
fi

# Verify expected subdirectories
_missing=0
for dir in Account Login WorldManager Zone00 Databases; do
    if [ -d "${DEPLOY_PATH}/${dir}" ]; then
        echo "  OK: ${dir}/"
    else
        echo "  MISSING: ${dir}/"
        _missing=1
    fi
done
if [ "${_missing}" -eq 1 ]; then
    echo ""
    echo "  Some directories are missing. Deploy will fail without them."
    read -p "  Continue anyway? [y/N] " -r
    [[ ! "${REPLY}" =~ ^[Yy]$ ]] && { echo "Aborted."; exit 0; }
fi
echo ""

# --- SA_PASSWORD ---
echo "SA_PASSWORD: SQL Server admin password (must meet SQL Server complexity rules)."
if [ -n "${SA_PASSWORD:-}" ]; then
    read -p "  SA_PASSWORD [****]: " input_sa_password
    SA_PASSWORD="${input_sa_password:-${SA_PASSWORD}}"
else
    read -p "  SA_PASSWORD: " SA_PASSWORD
fi

if [ -z "${SA_PASSWORD}" ]; then
    echo "ERROR: SA_PASSWORD is required."
    exit 1
fi
echo ""

# --- PORT_OFFSET (optional) ---
echo "PORT_OFFSET: Shift all ports by N (optional, for running multiple instances)."
echo "  Default ports: Login=9010, Patch=8080, API=5000"
read -p "  PORT_OFFSET [0]: " PORT_OFFSET
PORT_OFFSET="${PORT_OFFSET:-0}"
echo ""

# --- KEEP_ALIVE (optional) ---
echo "KEEP_ALIVE: Keep containers alive after process exit for debugging? [0/1]"
read -p "  KEEP_ALIVE [0]: " KEEP_ALIVE
KEEP_ALIVE="${KEEP_ALIVE:-0}"
echo ""

# --- Write config files ---
echo "Writing ${ENV_FILE}..."
cat > "${ENV_FILE}" << EOF
# Mimir deploy config — generated by mimir deploy setup
DEPLOY_PATH=${DEPLOY_PATH}
KEEP_ALIVE=${KEEP_ALIVE}
PORT_OFFSET=${PORT_OFFSET}
EOF

echo "Writing ${SECRETS_FILE}..."
cat > "${SECRETS_FILE}" << EOF
# Mimir deploy secrets — DO NOT commit this file
SA_PASSWORD=${SA_PASSWORD}
EOF

# Ensure secrets file is gitignored
GITIGNORE="${MIMIR_PROJ_DIR}/.gitignore"
if [ -f "${GITIGNORE}" ]; then
    if ! grep -qF '.mimir-deploy.secrets' "${GITIGNORE}"; then
        echo '.mimir-deploy.secrets' >> "${GITIGNORE}"
        echo "Added .mimir-deploy.secrets to .gitignore"
    fi
fi

# Ensure required directories exist
mkdir -p "${MIMIR_PROJ_DIR}/deployed/server" "${MIMIR_PROJ_DIR}/patches"

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Next steps:"
echo "  1. Build Docker images:    mimir deploy rebuild-sql"
echo "                             mimir deploy rebuild-game"
echo "  2. Start SQL Server:       mimir deploy start"
echo "  3. Check logs:             mimir deploy logs"
echo ""
echo "Config files:"
echo "  ${ENV_FILE}"
echo "  ${SECRETS_FILE}"
