using System.CommandLine;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Fiesta.Collab.Core;
using Fiesta.Collab.Core.Constraints;
using Fiesta.Collab.Core.Models;
using Fiesta.Collab.Core.Project;
using Fiesta.Collab.Core.Providers;
using Fiesta.Collab.Core.Templates;
using Fiesta.Collab.Shn;
using Fiesta.Collab.ShineTable;
using Fiesta.Collab.Sql;

var services = new ServiceCollection();
services.AddLogging(b => b.AddConsole().SetMinimumLevel(LogLevel.Information));
services.AddFiestaCore();
services.AddFiestaShn();
services.AddFiestaTextTables();
services.AddFiestaSql();

var sp = services.BuildServiceProvider();

var rootCommand = new RootCommand("fiesta - Fiesta Online server data toolkit");

// Shared --project/-p option used by commands that also have other positional args
Option<DirectoryInfo?> MakeProjectOption()
{
    var opt = new Option<DirectoryInfo?>("--project",
        "Path to fiesta project directory (defaults to current directory)")
    {
        Arity = ArgumentArity.ZeroOrOne
    };
    opt.AddAlias("-p");
    return opt;
}


// --- init command ---

var initCommand = new Command("init", "Create a new fiesta project directory with a skeleton fiesta.json");
var initProjectArg = new Argument<DirectoryInfo>("project", "Path to the new fiesta project directory to create");
initCommand.AddArgument(initProjectArg);

initCommand.SetHandler(async (DirectoryInfo project) =>
{
    var logger = sp.GetRequiredService<ILogger<Program>>();
    var projectService = sp.GetRequiredService<IProjectService>();

    if (File.Exists(Path.Combine(project.FullName, "fiesta.json")))
    {
        logger.LogError("fiesta.json already exists in {Dir}. Delete it first or choose a different directory.", project.FullName);
        return;
    }

    Directory.CreateDirectory(project.FullName);
    Directory.CreateDirectory(Path.Combine(project.FullName, "data"));
    EnvironmentStore.EnsureEnvDir(project.FullName);

    await projectService.SaveProjectAsync(project.FullName, new FiestaProject());

    void WriteIfMissing(string path, string content)
    {
        if (File.Exists(path)) return;
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, content);
        logger.LogInformation("Created {Path}", Path.GetRelativePath(project.FullName, path));
    }

    var projectName = project.Name;

    WriteIfMissing(Path.Combine(project.FullName, ".gitignore"),
        "# Generated build output (regenerated by `fiesta build`)\n" +
        "build/\n" +
        "\n" +
        "# OS\n" +
        ".DS_Store\n" +
        "Thumbs.db\n");

    WriteIfMissing(Path.Combine(project.FullName, "data", ".gitkeep"), "");

    WriteIfMissing(Path.Combine(project.FullName, "README.md"),
        $"# {projectName}\n" +
        "\n" +
        "A Fiesta Online content project, managed with the `fiesta` toolkit\n" +
        "([ik-fiesta-collab](https://github.com/IkaronClaude/ik-fiesta-collab)).\n" +
        "Game data lives as git-tracked JSON under `data/`; edit with SQL, build back to SHN/txt.\n" +
        "\n" +
        "## Workflow\n" +
        "\n" +
        "```bash\n" +
        "# 1. Register your data sources\n" +
        "fiesta env server init /path/to/Server --type server\n" +
        "fiesta env client init /path/to/ClientSource/ressystem --type client\n" +
        "\n" +
        "# 2. Generate merge rules, then import -> data/*.json\n" +
        "fiesta init-template\n" +
        "fiesta import\n" +
        "\n" +
        "# 3. Edit with SQL, rebuild, commit\n" +
        "fiesta edit \"UPDATE ItemInfo SET AC = 100 WHERE InxName = 'NoviceSword'\"\n" +
        "fiesta build --all\n" +
        "git add data/ && git commit -m \"...\"\n" +
        "```\n" +
        "\n" +
        "## Layout\n" +
        "\n" +
        "```\n" +
        $"{projectName}/\n" +
        "  fiesta.json            # project manifest (the marker the CLI looks for)\n" +
        "  fiesta.template.json   # merge rules (generated by init-template, then hand-tuned)\n" +
        "  data/                  # imported game data as JSON -- commit this\n" +
        "  environments/          # per-env import/build config\n" +
        "  build/                 # build output -- gitignored\n" +
        "```\n" +
        "\n" +
        "## Reference\n" +
        "\n" +
        "- `fiesta --help` -- all commands\n" +
        "- `fiesta env all list` -- show environment configs\n" +
        "- `fiesta validate` -- check foreign-key constraints\n" +
        "- `fiesta shn <file>` -- inspect a raw SHN file\n" +
        "\n" +
        "Client patches: [ik-fiesta-patch-server](https://github.com/IkaronClaude/ik-fiesta-patch-server). " +
        "Deploy: [ik-fiesta-collab-pipelines](https://github.com/IkaronClaude/ik-fiesta-collab-pipelines).\n");

    logger.LogInformation("Created fiesta project at {Dir}", project.FullName);
    logger.LogInformation("Next steps:");
    logger.LogInformation("  cd {Dir}", project.FullName);
    logger.LogInformation("  fiesta env server init /path/to/Server --type server");
    logger.LogInformation("  fiesta init-template && fiesta import");
    logger.LogInformation("  fiesta build --all");
}, initProjectArg);

// --- import command ---
var importCommand = new Command("import", "Import data files into a fiesta project using environments from fiesta.json");
var importProjectOpt = MakeProjectOption();
var importReimportOption = new Option<bool>("--reimport", "Wipe data/ and build/ directories before importing for a clean re-import");
importCommand.AddOption(importProjectOpt);
importCommand.AddOption(importReimportOption);

importCommand.SetHandler(async (DirectoryInfo? projectOpt, bool reimport) =>
{
    var logger = sp.GetRequiredService<ILogger<Program>>();
    var project = ResolveProjectOrExit(projectOpt, logger);
    var projectService = sp.GetRequiredService<IProjectService>();
    var providers = sp.GetServices<IDataProvider>().ToList();

    var manifest = await projectService.LoadProjectAsync(project.FullName);

    if (reimport)
    {
        var dataDir = Path.Combine(project.FullName, "data");
        var buildDir = Path.Combine(project.FullName, "build");
        if (Directory.Exists(dataDir))
        {
            logger.LogInformation("--reimport: deleting {Dir}", dataDir);
            Directory.Delete(dataDir, recursive: true);
        }
        if (Directory.Exists(buildDir))
        {
            logger.LogInformation("--reimport: deleting {Dir}", buildDir);
            Directory.Delete(buildDir, recursive: true);
        }
        manifest.Tables.Clear();
        logger.LogInformation("--reimport: cleared tables index — starting fresh import");
    }

    var allEnvs = EnvironmentStore.LoadAll(project.FullName);
    if (allEnvs.Count == 0)
    {
        logger.LogError("No environments configured. Use: fiesta env <name> init <importPath>");
        return;
    }

    // Load template for merge actions
    var template = await TemplateResolver.LoadAsync(project.FullName);

    // Phase 1: Read all tables from each environment into memory
    var rawTables = new Dictionary<(string tableName, string envName), TableFile>();
    var rawRelDirs = new Dictionary<(string tableName, string envName), string>(); // track source-relative dirs

    foreach (var (envName, envConfig) in allEnvs)
    {
        if (envConfig.ImportPath == null)
        {
            logger.LogWarning("Skipping environment {Env}: import-path not set. Use: fiesta env {Env} set import-path <path>", envName, envName);
            continue;
        }
        var sourceDir = new DirectoryInfo(envConfig.ImportPath);
        if (!sourceDir.Exists)
        {
            logger.LogWarning("Import path does not exist for environment {Env}: {Path}", envName, envConfig.ImportPath);
            continue;
        }

        logger.LogInformation("Scanning environment {Env}: {Path}", envName, sourceDir.FullName);
        var tables = await ReadAllTables(sourceDir, providers, logger);

        foreach (var (tableName, (tableFile, relDir)) in tables)
        {
            rawTables[(tableName, envName)] = tableFile;
            rawRelDirs[(tableName, envName)] = relDir;
            logger.LogDebug("Read {Table} from {Env} ({Rows} rows, relDir={Dir})", tableName, envName, tableFile.Data.Count, relDir);
        }

        logger.LogInformation("Read {Count} tables from {Env}", tables.Count, envName);
    }

    // Phase 2: Execute merge actions from template
    var mergedTables = new Dictionary<string, TableFile>();
    var allEnvMetadata = new Dictionary<string, Dictionary<string, EnvMergeMetadata>>(); // tableName → envName → metadata
    int totalConflicts = 0;

    var mergeActions = template.Actions.Where(a => a.Action is "copy" or "merge").ToList();
    var tablesHandledByActions = new HashSet<string>();
    var tableTargetEnvs = new Dictionary<string, string>(); // merged tableName → env that seeded the table via copy

    foreach (var action in mergeActions)
    {
        if (action.Action == "copy" && action.From != null && action.To != null)
        {
            var key = (action.From.Table, action.From.Env);
            if (rawTables.TryGetValue(key, out var raw))
            {
                // Tag every row with the source env so that after a subsequent merge,
                // target-only rows are correctly excluded from other envs at build time.
                var taggedRowEnvs = Enumerable.Repeat<List<string>?>([action.From.Env], raw.Data.Count).ToList();
                mergedTables[action.To] = new TableFile
                {
                    Header = raw.Header,
                    Columns = raw.Columns,
                    Data = raw.Data,
                    RowEnvironments = taggedRowEnvs
                };
                tablesHandledByActions.Add(action.To);
                tableTargetEnvs[action.To] = action.From.Env;

                // Store base env column order and source path
                if (!allEnvMetadata.ContainsKey(action.To))
                    allEnvMetadata[action.To] = new();
                allEnvMetadata[action.To][action.From.Env] = new EnvMergeMetadata
                {
                    ColumnOrder = raw.Columns.Select(c => c.Name).ToList(),
                    ColumnOverrides = new(),
                    ColumnRenames = new(),
                    SourceRelDir = rawRelDirs.GetValueOrDefault(key, ""),
                    OutputName = action.OutputName,
                    FormatMetadata = ExtractFormatMetadata(raw.Header.Metadata)
                };

                logger.LogInformation("Copy: {From}@{Env} → {To}", action.From.Table, action.From.Env, action.To);
            }
            else
            {
                logger.LogWarning("Copy action: table {Table} not found in environment {Env}",
                    action.From.Table, action.From.Env);
            }
        }
        else if (action.Action == "merge" && action.From != null && action.Into != null && action.On != null)
        {
            var key = (action.From.Table, action.From.Env);
            if (!rawTables.TryGetValue(key, out var source))
            {
                logger.LogWarning("Merge action: table {Table} not found in environment {Env}",
                    action.From.Table, action.From.Env);
                continue;
            }

            if (!mergedTables.TryGetValue(action.Into, out var target))
            {
                logger.LogWarning("Merge action: target table {Table} not yet created (need a copy action first)",
                    action.Into);
                continue;
            }

            var strategy = action.ColumnStrategy ?? "auto";
            var conflictStrategy = action.ConflictStrategy ?? "report";
            var targetEnvName = tableTargetEnvs.GetValueOrDefault(action.Into);
            var result = TableMerger.Merge(target, source, action.On, action.From.Env, strategy, conflictStrategy, targetEnvName);
            mergedTables[action.Into] = result.Table;

            // Accumulate env metadata
            if (!allEnvMetadata.ContainsKey(action.Into))
                allEnvMetadata[action.Into] = new();
            foreach (var (eName, eMeta) in result.EnvMetadata)
                allEnvMetadata[action.Into][eName] = eMeta;

                // Set SourceRelDir on the env metadata from rawRelDirs
            foreach (var (eName, eMeta) in result.EnvMetadata)
            {
                var relKey = (action.From.Table, eName);
                eMeta.SourceRelDir = rawRelDirs.GetValueOrDefault(relKey, "");
            }

            if (result.Conflicts.Count > 0)
            {
                totalConflicts += result.Conflicts.Count;
                if (conflictStrategy == "split")
                {
                    logger.LogInformation("Resolved {Count} value conflict(s) in {Table} via column splitting",
                        result.Conflicts.Count, action.Into);
                }
                else
                {
                    foreach (var c in result.Conflicts.Take(5))
                        logger.LogError("CONFLICT in {Table}: key={Key} col={Col} target={TVal} source={SVal}",
                            action.Into, c.JoinKey, c.Column, c.TargetValue, c.SourceValue);
                    if (result.Conflicts.Count > 5)
                        logger.LogError("  ... and {More} more conflicts in {Table}",
                            result.Conflicts.Count - 5, action.Into);
                }
            }

            if (result.DuplicateJoinKeys.Count > 0)
            {
                logger.LogWarning("DUPLICATE JOIN KEYS in {Table}@{Env}: {Keys}",
                    action.From.Table, action.From.Env,
                    string.Join(", ", result.DuplicateJoinKeys.Take(10))
                    + (result.DuplicateJoinKeys.Count > 10
                        ? $" ... and {result.DuplicateJoinKeys.Count - 10} more" : ""));
            }

            logger.LogInformation("Merge: {From}@{Env} → {Into} ({Conflicts} conflicts)",
                action.From.Table, action.From.Env, action.Into, result.Conflicts.Count);
        }
    }

    // Phase 3: Tables without merge actions — copy directly if only in one env
    var allTableNames = rawTables.Keys.Select(k => k.tableName).Distinct();
    foreach (var tableName in allTableNames)
    {
        if (tablesHandledByActions.Contains(tableName)) continue;

        var envs = rawTables.Keys.Where(k => k.tableName == tableName).Select(k => k.envName).ToList();
        if (envs.Count == 1)
        {
            var key = (tableName, envs[0]);
            mergedTables[tableName] = rawTables[key];

            // Track env metadata for passthrough tables too (for build path reconstruction)
            if (!allEnvMetadata.ContainsKey(tableName))
                allEnvMetadata[tableName] = new();
            allEnvMetadata[tableName][envs[0]] = new EnvMergeMetadata
            {
                ColumnOrder = rawTables[key].Columns.Select(c => c.Name).ToList(),
                ColumnOverrides = new(),
                ColumnRenames = new(),
                SourceRelDir = rawRelDirs.GetValueOrDefault(key, ""),
                FormatMetadata = ExtractFormatMetadata(rawTables[key].Header.Metadata)
            };

            logger.LogDebug("Passthrough: {Table} (only in {Env})", tableName, envs[0]);
        }
        else
        {
            // Multiple envs but no merge action — check if identical
            var first = rawTables[(tableName, envs[0])];
            bool allIdentical = true;
            foreach (var env in envs.Skip(1))
            {
                var diff = TableComparer.FindDifference(first, rawTables[(tableName, env)]);
                if (diff != null)
                {
                    allIdentical = false;
                    logger.LogWarning("Table {Table} exists in multiple envs but has no merge action and differs: {Diff}",
                        tableName, diff);
                    break;
                }
            }
            if (allIdentical)
            {
                mergedTables[tableName] = first;

                // Track env metadata for all envs (identical table, all envs have it)
                if (!allEnvMetadata.ContainsKey(tableName))
                    allEnvMetadata[tableName] = new();
                foreach (var env in envs)
                {
                    var key = (tableName, env);
                    allEnvMetadata[tableName][env] = new EnvMergeMetadata
                    {
                        ColumnOrder = first.Columns.Select(c => c.Name).ToList(),
                        ColumnOverrides = new(),
                        ColumnRenames = new(),
                        SourceRelDir = rawRelDirs.GetValueOrDefault(key, ""),
                        FormatMetadata = ExtractFormatMetadata(rawTables[key].Header.Metadata)
                    };
                }

                logger.LogDebug("Passthrough: {Table} (identical across envs)", tableName);
            }
            else
            {
                // Just take the first env's version and warn
                mergedTables[tableName] = first;
            }
        }
    }

    // Phase 4: Write merged tables and update manifest
    manifest.Tables.Clear();
    int merged = 0;

    foreach (var (tableName, tableFile) in mergedTables.OrderBy(kv => kv.Key))
    {
        // Determine relative path from source format.
        // Use the internal name (tableName) as the JSON file key — not the source TableName —
        // so same-filename tables at different paths (e.g. "View.ActionViewInfo" vs "ActionViewInfo")
        // get distinct JSON files and don't overwrite each other.
        var relativePath = $"data/{tableFile.Header.SourceFormat}/{tableName}.json";

        // Enrich metadata with env info
        if (allEnvMetadata.TryGetValue(tableName, out var envMetas) && envMetas.Count > 0)
        {
            var metadata = tableFile.Header.Metadata ?? new Dictionary<string, object>();

            // Mark origin: "merged" for multi-env, env name for single-env
            if (envMetas.Count > 1)
                metadata[SourceOrigin.MetadataKey] = EnvironmentInfo.MergedOrigin;
            else
                metadata[SourceOrigin.MetadataKey] = envMetas.Keys.First();

            // Store per-env metadata (including sourceRelDir and format metadata)
            foreach (var (eName, eMeta) in envMetas)
            {
                metadata[eName] = new Dictionary<string, object?>
                {
                    ["columnOrder"] = eMeta.ColumnOrder,
                    ["columnOverrides"] = eMeta.ColumnOverrides.Count > 0 ? eMeta.ColumnOverrides : null,
                    ["columnRenames"] = eMeta.ColumnRenames.Count > 0 ? eMeta.ColumnRenames : null,
                    ["sourceRelDir"] = eMeta.SourceRelDir,
                    ["outputName"] = eMeta.OutputName,
                    ["formatMetadata"] = eMeta.FormatMetadata
                };
            }

            var enrichedFile = new TableFile
            {
                Header = new TableHeader
                {
                    TableName = tableFile.Header.TableName,
                    SourceFormat = tableFile.Header.SourceFormat,
                    Metadata = metadata
                },
                Columns = tableFile.Columns,
                Data = tableFile.Data,
                RowEnvironments = tableFile.RowEnvironments
            };

            await projectService.WriteTableFileAsync(project.FullName, relativePath, enrichedFile);
            if (envMetas.Count > 1) merged++;
        }
        else
        {
            await projectService.WriteTableFileAsync(project.FullName, relativePath, tableFile);
        }

        manifest.Tables[tableName] = relativePath;
    }

    await projectService.SaveProjectAsync(project.FullName, manifest);

    logger.LogInformation("Import complete: {Total} tables ({Merged} merged, {Conflicts} conflicts)",
        manifest.Tables.Count, merged, totalConflicts);


    static Dictionary<string, object>? ExtractFormatMetadata(Dictionary<string, object>? meta)
    {
        if (meta == null) return null;
        var result = new Dictionary<string, object>();
        foreach (var k in new[] { "cryptHeader", "header" })
            if (meta.TryGetValue(k, out var v) && v != null) result[k] = v;
        return result.Count > 0 ? result : null;
    }

}, importProjectOpt, importReimportOption);

// --- reimport command ---
var reimportCommand = new Command("reimport", "Wipe data/ and build/, re-import all environments, and rebuild");
var reimportProjectOpt = MakeProjectOption();
reimportCommand.AddOption(reimportProjectOpt);

reimportCommand.SetHandler(async (DirectoryInfo? projectOpt) =>
{
    var logger = sp.GetRequiredService<ILogger<Program>>();
    var project = ResolveProjectOrExit(projectOpt, logger);

    logger.LogInformation("Starting reimport for {Dir}", project.FullName);

    var importResult = await rootCommand.InvokeAsync(new[] { "import", "--project", project.FullName, "--reimport" });
    if (importResult != 0)
    {
        logger.LogError("Import step failed, aborting.");
        return;
    }

    // Run: build --all (this will also seed pack baselines for patchable envs)
    await rootCommand.InvokeAsync(new[] { "build", "--project", project.FullName, "--all" });

}, reimportProjectOpt);

// --- build command ---
var buildCommand = new Command("build", "Build data files from a fiesta project for a specific environment");
var buildProjectOption = MakeProjectOption();
var buildOutputOption = new Option<DirectoryInfo?>("--output", "Output directory (overrides configured buildPath; ignored with --all)")
{
    Arity = ArgumentArity.ZeroOrOne
};
buildOutputOption.AddAlias("-o");
var buildEnvOption = new Option<string?>("--env", "Environment to build for (e.g. server, client)");
buildEnvOption.AddAlias("-e");
var buildAllOption = new Option<bool>("--all", "Build all environments to their configured buildPaths");
buildCommand.AddOption(buildProjectOption);
buildCommand.AddOption(buildOutputOption);
buildCommand.AddOption(buildEnvOption);
buildCommand.AddOption(buildAllOption);

buildCommand.SetHandler(async (DirectoryInfo? projectOpt, DirectoryInfo? outputOpt, string? envName, bool buildAll) =>
{
    var logger = sp.GetRequiredService<ILogger<Program>>();
    var project = ResolveProjectOrExit(projectOpt, logger);
    var projectService = sp.GetRequiredService<IProjectService>();
    var providers = sp.GetServices<IDataProvider>().ToDictionary(p => p.FormatId);

    var manifest = await projectService.LoadProjectAsync(project.FullName);
    var template = await TemplateResolver.LoadAsync(project.FullName);
    var allEnvs = EnvironmentStore.LoadAll(project.FullName);

    // Default to --all when no env or output specified
    if (!buildAll && envName == null && outputOpt == null)
        buildAll = true;

    // Determine which environments to build
    var envsToBuild = new Dictionary<string, string>(); // envName → outputDir
    if (buildAll)
    {
        foreach (var (eName, eConfig) in allEnvs)
        {
            var buildPath = eConfig.BuildPath ?? Path.Combine("build", eName);
            var fullPath = Path.IsPathRooted(buildPath) ? buildPath : Path.Combine(project.FullName, buildPath);
            envsToBuild[eName] = fullPath;
        }
    }
    else if (envName != null)
    {
        string outputDir;
        if (outputOpt != null)
        {
            outputDir = outputOpt.FullName;
        }
        else if (allEnvs.TryGetValue(envName, out var eConfig))
        {
            var buildPath = eConfig.BuildPath ?? Path.Combine("build", envName);
            outputDir = Path.IsPathRooted(buildPath) ? buildPath : Path.Combine(project.FullName, buildPath);
        }
        else
        {
            logger.LogError("Environment '{Env}' not found. Use 'fiesta env {Env} init' to configure it.", envName, envName);
            return;
        }
        envsToBuild[envName] = outputDir;
    }
    else
    {
        // Legacy: explicit --output
        envsToBuild[""] = outputOpt!.FullName;
    }

    // Load env metadata from template (for merged table splitting)
    // Build a map of tableName → envName → EnvMergeMetadata from persisted JSON metadata
    var envMetadataMap = new Dictionary<string, Dictionary<string, EnvMergeMetadata>>();

    foreach (var (eName, outputDir) in envsToBuild)
    {
        Directory.CreateDirectory(outputDir);
        int built = 0;

        logger.LogInformation("Building {Env} to {Output}", eName == "" ? "all" : eName, outputDir);

        // Buffer for multi-section files that share a sourceFile (e.g. ServerInfo.txt with multiple #DEFINE sections)
        var groupedEntries = new Dictionary<(IDataProvider provider, string dir, string sourceFile), List<TableEntry>>();

        foreach (var (name, entryPath) in manifest.Tables)
        {
            var tableFile = await projectService.ReadTableFileAsync(project.FullName, entryPath);

            // Check origin metadata to determine how to handle this table
            var origin = tableFile.Header.Metadata?.TryGetValue(SourceOrigin.MetadataKey, out var o) == true
                ? o?.ToString() : null;

            // Extract per-env metadata for this table
            EnvMergeMetadata? envMeta = null;
            if (eName != "" && tableFile.Header.Metadata != null
                && tableFile.Header.Metadata.TryGetValue(eName, out var rawMeta)
                && rawMeta is System.Text.Json.JsonElement je)
            {
                envMeta = EnvMergeMetadata.FromJsonElement(je);
            }

            TableFile outputTable;
            if (origin == EnvironmentInfo.MergedOrigin && eName != "")
            {
                // Multi-env merged table — split for this env
                if (envMeta == null)
                {
                    logger.LogDebug("Skipping {Table} for env {Env} (no env metadata)", name, eName);
                    continue;
                }
                outputTable = TableSplitter.Split(tableFile, eName, envMeta);
            }
            else if (origin != null && origin != EnvironmentInfo.MergedOrigin && origin != eName && eName != "")
            {
                // Single-env table that belongs to a different env — skip
                logger.LogDebug("Skipping {Table} for env {Env} (belongs to {Origin})", name, eName, origin);
                continue;
            }
            else
            {
                outputTable = tableFile;
            }

            var entry = new TableEntry
            {
                Schema = new TableSchema
                {
                    TableName = outputTable.Header.TableName,
                    SourceFormat = outputTable.Header.SourceFormat,
                    Columns = outputTable.Columns,
                    Metadata = outputTable.Header.Metadata
                },
                Rows = outputTable.Data
            };

            if (!providers.TryGetValue(entry.Schema.SourceFormat, out var provider))
            {
                logger.LogWarning("No provider for format {Format}, skipping {Table}",
                    entry.Schema.SourceFormat, name);
                continue;
            }

            try
            {
                var ext = provider.SupportedExtensions[0].TrimStart('.');

                // Use sourceRelDir to reconstruct original directory structure
                var relDir = envMeta?.SourceRelDir;
                var dir = string.IsNullOrEmpty(relDir) ? outputDir : Path.Combine(outputDir, relDir);

                // Check if this table has a sourceFile (multi-section txt files)
                var sourceFile = entry.Schema.Metadata?.TryGetValue("sourceFile", out var sf) == true
                    ? sf?.ToString() : null;

                if (!string.IsNullOrEmpty(sourceFile))
                {
                    // Buffer for grouped write — multiple sections → one file
                    var key = (provider, dir, sourceFile);
                    if (!groupedEntries.TryGetValue(key, out var group))
                    {
                        group = [];
                        groupedEntries[key] = group;
                    }
                    group.Add(entry);
                    built++;
                }
                else
                {
                    // Single-table file (SHN, etc.) — write immediately
                    // Use outputName override when set (e.g. "GBHouse__server" → "GBHouse.shn")
                    var outputFileName = envMeta?.OutputName ?? name;
                    Directory.CreateDirectory(dir);
                    await provider.WriteAsync(Path.Combine(dir, $"{outputFileName}.{ext}"), [entry]);
                    built++;
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Failed to build {Table}", name);
            }
        }

        // Write grouped multi-section files (configtable/shinetable with shared sourceFile)
        foreach (var ((gProvider, gDir, gSourceFile), entries) in groupedEntries)
        {
            try
            {
                // Sort by sectionIndex to preserve original file order
                entries.Sort((a, b) =>
                {
                    int idxA = GetSectionIndex(a.Schema.Metadata);
                    int idxB = GetSectionIndex(b.Schema.Metadata);
                    return idxA.CompareTo(idxB);
                });
                Directory.CreateDirectory(gDir);
                await gProvider.WriteAsync(Path.Combine(gDir, gSourceFile), entries);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Failed to build grouped file {File}", gSourceFile);
            }
        }

        logger.LogInformation("Built {Count} files for {Env}", built, eName == "" ? "all" : eName);

        // Process copyFile actions — copy raw passthrough files (e.g. _ServerGroup.txt)
        foreach (var action in template.Actions.Where(a => a.Action == "copyFile"))
        {
            if (action.Env == null || action.Path == null) continue;
            // Only process for the matching env (or legacy "" mode = copy all)
            if (eName != "" && action.Env != eName) continue;

            if (!allEnvs.TryGetValue(action.Env, out var srcEnvConfig))
            {
                logger.LogWarning("CopyFile: environment '{Env}' not found", action.Env);
                continue;
            }

            if (srcEnvConfig.ImportPath == null)
            {
                logger.LogWarning("CopyFile: environment '{Env}' has no import-path configured", action.Env);
                continue;
            }

            var normalizedPath = action.Path.Replace('/', Path.DirectorySeparatorChar);
            var srcFile = Path.Combine(srcEnvConfig.ImportPath, normalizedPath);
            var destFile = Path.Combine(outputDir, normalizedPath);

            if (!File.Exists(srcFile))
            {
                logger.LogWarning("CopyFile: source not found: {Path}", srcFile);
                continue;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(destFile)!);
            File.Copy(srcFile, destFile, overwrite: true);
            logger.LogInformation("CopyFile: {Path}", action.Path);
        }

        // Overrides: copy everything from overridesPath verbatim, winning over all other output
        var currentEnvConfig = eName != "" && allEnvs.TryGetValue(eName, out var ec) ? ec : null;
        if (currentEnvConfig?.OverridesPath != null)
        {
            var overridesDir = new DirectoryInfo(currentEnvConfig.OverridesPath);
            if (!overridesDir.Exists)
            {
                logger.LogWarning("Override path does not exist for {Env}: {Path}", eName, currentEnvConfig.OverridesPath);
            }
            else
            {
                var overrideFiles = overridesDir.EnumerateFiles("*", SearchOption.AllDirectories);
                int overrideCount = 0;
                foreach (var f in overrideFiles)
                {
                    var relPath = Path.GetRelativePath(overridesDir.FullName, f.FullName);
                    var destFile = Path.Combine(outputDir, relPath);
                    Directory.CreateDirectory(Path.GetDirectoryName(destFile)!);
                    File.Copy(f.FullName, destFile, overwrite: true);
                    overrideCount++;
                }
                logger.LogInformation("Overrides: copied {Count} file(s) from {Path}", overrideCount, currentEnvConfig.OverridesPath);
            }
        }

    }

}, buildProjectOption, buildOutputOption, buildEnvOption, buildAllOption);

// --- query command ---
var queryCommand = new Command("query", "Run SQL against a fiesta project");
var queryProjectOption = MakeProjectOption();
var sqlArg = new Argument<string>("sql", "SQL query to execute");
queryCommand.AddOption(queryProjectOption);
queryCommand.AddArgument(sqlArg);

queryCommand.SetHandler(async (DirectoryInfo? projectOpt, string sql) =>
{
    var logger = sp.GetRequiredService<ILogger<Program>>();
    var project = ResolveProjectOrExit(projectOpt, logger);
    var projectService = sp.GetRequiredService<IProjectService>();
    using var engine = sp.GetRequiredService<ISqlEngine>();

    var manifest = await projectService.LoadProjectAsync(project.FullName);
    await LoadTablesWithConstraints(engine, projectService, manifest, project.FullName, logger);

    logger.LogInformation("Loaded {Count} tables, executing query...", manifest.Tables.Count);

    var results = engine.Query(sql);
    foreach (var row in results)
    {
        var values = row.Select(kv => $"{kv.Key}={kv.Value}");
        Console.WriteLine(string.Join(" | ", values));
    }

    Console.WriteLine($"({results.Count} rows)");

}, queryProjectOption, sqlArg);

// --- dump command (diagnostic) ---
var dumpCommand = new Command("dump", "Dump decrypted SHN file structure for debugging");
var dumpFilesArg = new Argument<string[]>("files", "SHN files to dump");
dumpCommand.AddArgument(dumpFilesArg);
dumpCommand.SetHandler((string[] files) => Fiesta.Collab.Cli.DiagnosticDump.DumpShnFile(files[0]), dumpFilesArg);

// --- analyze-types command (diagnostic) ---
var analyzeCommand = new Command("analyze-types", "Analyze all SHN type codes across a directory");
var analyzeDirArg = new Argument<DirectoryInfo>("directory", "Path to SHN files directory");
analyzeCommand.AddArgument(analyzeDirArg);
analyzeCommand.SetHandler((DirectoryInfo dir) => Fiesta.Collab.Cli.TypeAnalysis.AnalyzeAllTypes(dir.FullName), analyzeDirArg);

// --- validate command ---
var validateCommand = new Command("validate", "Validate a fiesta project against constraint rules");
var validateProjectOpt = MakeProjectOption();
validateCommand.AddOption(validateProjectOpt);

validateCommand.SetHandler(async (DirectoryInfo? projectOpt) =>
{
    var logger = sp.GetRequiredService<ILogger<Program>>();
    var project = ResolveProjectOrExit(projectOpt, logger);
    var projectService = sp.GetRequiredService<IProjectService>();
    using var engine = sp.GetRequiredService<ISqlEngine>();

    var manifest = await projectService.LoadProjectAsync(project.FullName);
    var constraints = await LoadDefinitions(project.FullName, logger);

    if (constraints.Constraints.Count == 0)
    {
        logger.LogWarning("No constraints found. Create {File} or {Template} to add constraints.",
            DefinitionResolver.DefinitionsFileName, TemplateResolver.TemplateFileName);
        return;
    }

    // Load with FK constraints in schema (empty values mapped to NULL)
    await LoadTablesWithConstraints(engine, projectService, manifest, project.FullName, logger);

    // Resolve for detailed violation reporting
    var resolved = DefinitionResolver.Resolve(constraints, manifest);
    logger.LogInformation("Resolved {Count} constraint bindings from {RuleCount} rules",
        resolved.Count, constraints.Constraints.Count);

    int violations = 0;
    int checks = 0;

    foreach (var constraint in resolved)
    {
        var sourceTableFile = await projectService.ReadTableFileAsync(
            project.FullName, manifest.Tables[constraint.SourceTable]);
        var matchingColumns = sourceTableFile.Columns
            .Where(c => DefinitionResolver.GlobMatch(c.Name, constraint.ColumnPattern))
            .ToList();

        foreach (var col in matchingColumns)
        {
            checks++;

            // Empty values are already NULL from loading, so just check non-null values
            var sql = $@"SELECT s.[{col.Name}] as value, COUNT(*) as cnt
                FROM [{constraint.SourceTable}] s
                WHERE s.[{col.Name}] IS NOT NULL
                  AND s.[{col.Name}] NOT IN (SELECT [{constraint.TargetColumn}] FROM [{constraint.TargetTable}])
                GROUP BY s.[{col.Name}]
                LIMIT 10";

            try
            {
                var results = engine.Query(sql);
                if (results.Count > 0)
                {
                    violations += results.Count;
                    var desc = constraint.Rule.Description ?? $"{constraint.SourceTable}.{col.Name}";
                    Console.WriteLine($"VIOLATION: {constraint.SourceTable}.{col.Name} -> {constraint.TargetTable}.{constraint.TargetColumn}");
                    Console.WriteLine($"  Rule: {desc}");
                    foreach (var row in results.Take(5))
                    {
                        Console.WriteLine($"  Missing: \"{row["value"]}\" ({row["cnt"]} occurrences)");
                    }
                    if (results.Count > 5)
                        Console.WriteLine($"  ... and {results.Count - 5} more distinct values");
                    Console.WriteLine();
                }
            }
            catch (Exception ex)
            {
                logger.LogWarning("Constraint check failed for {Source}.{Column} -> {Target}.{TargetCol}: {Error}",
                    constraint.SourceTable, col.Name, constraint.TargetTable, constraint.TargetColumn, ex.Message);
            }
        }
    }

    if (violations == 0)
        Console.WriteLine($"All {checks} constraint checks passed.");
    else
        Console.WriteLine($"{violations} violations found across {checks} checks.");

}, validateProjectOpt);

// --- edit command ---
var editCommand = new Command("edit", "Run SQL to modify project data and save changes back to JSON");
var editProjectOption = MakeProjectOption();
var editSqlArg = new Argument<string>("sql", "SQL statement(s) to execute (UPDATE, INSERT, DELETE)");
editCommand.AddOption(editProjectOption);
editCommand.AddArgument(editSqlArg);

editCommand.SetHandler(async (DirectoryInfo? projectOpt, string sql) =>
{
    var logger = sp.GetRequiredService<ILogger<Program>>();
    var project = ResolveProjectOrExit(projectOpt, logger);
    var projectService = sp.GetRequiredService<IProjectService>();
    using var engine = sp.GetRequiredService<ISqlEngine>();

    var manifest = await projectService.LoadProjectAsync(project.FullName);

    // Load all tables, preserving headers and row-environment annotations for write-back
    var tableHeaders = new Dictionary<string, TableHeader>();
    var tableSchemas = new Dictionary<string, TableSchema>();
    var tableRowEnvironments = new Dictionary<string, IReadOnlyList<List<string>?>?>();

    foreach (var (name, entryPath) in manifest.Tables)
    {
        var tableFile = await projectService.ReadTableFileAsync(project.FullName, entryPath);
        var schema = new TableSchema
        {
            TableName = name,   // use manifest key — header TableName may collide across envs
            SourceFormat = tableFile.Header.SourceFormat,
            Columns = tableFile.Columns,
            Metadata = tableFile.Header.Metadata
        };

        tableHeaders[name] = tableFile.Header;
        tableSchemas[name] = schema;
        tableRowEnvironments[name] = tableFile.RowEnvironments;
        engine.LoadTable(new TableEntry { Schema = schema, Rows = tableFile.Data });
    }

    logger.LogInformation("Loaded {Count} tables", manifest.Tables.Count);

    // Execute modification SQL
    var affected = engine.Execute(sql);
    logger.LogInformation("Executed: {Affected} rows affected", affected);

    if (affected == 0)
    {
        Console.WriteLine("No rows changed, nothing to save.");
        return;
    }

    // Extract all tables and save back to JSON
    int saved = 0;
    foreach (var (name, entryPath) in manifest.Tables)
    {
        var schema = tableSchemas[name];
        var extracted = engine.ExtractTable(schema);

        var tableFile = new TableFile
        {
            Header = tableHeaders[name],
            Columns = schema.Columns,
            Data = extracted.Rows,
            RowEnvironments = tableRowEnvironments.GetValueOrDefault(name)
        };

        await projectService.WriteTableFileAsync(project.FullName, entryPath, tableFile);
        saved++;
    }

    logger.LogInformation("Saved {Count} tables back to project", saved);
    Console.WriteLine($"{affected} rows modified, {saved} tables saved.");

}, editProjectOption, editSqlArg);

// --- shell command (interactive SQL) ---
var shellCommand = new Command("shell", "Interactive SQL shell against a fiesta project");
var shellProjectOpt = MakeProjectOption();
shellCommand.AddOption(shellProjectOpt);

shellCommand.SetHandler(async (DirectoryInfo? projectOpt) =>
{
    var logger = sp.GetRequiredService<ILogger<Program>>();
    var project = ResolveProjectOrExit(projectOpt, logger);
    var projectService = sp.GetRequiredService<IProjectService>();
    using var engine = sp.GetRequiredService<ISqlEngine>();

    var manifest = await projectService.LoadProjectAsync(project.FullName);
    var definitions = await LoadDefinitions(project.FullName, logger);

    // Load all tables, preserving headers and row-environment annotations for write-back
    var tableHeaders = new Dictionary<string, TableHeader>();
    var tableSchemas = new Dictionary<string, TableSchema>();
    var tableRowEnvironments = new Dictionary<string, IReadOnlyList<List<string>?>?>();

    foreach (var (name, entryPath) in manifest.Tables)
    {
        var tableFile = await projectService.ReadTableFileAsync(project.FullName, entryPath);
        var schema = new TableSchema
        {
            TableName = name,   // use manifest key — header TableName may collide across envs
            SourceFormat = tableFile.Header.SourceFormat,
            Columns = tableFile.Columns,
            Metadata = tableFile.Header.Metadata
        };
        tableHeaders[name] = tableFile.Header;
        tableSchemas[name] = schema;
        tableRowEnvironments[name] = tableFile.RowEnvironments;
        engine.LoadTable(new TableEntry { Schema = schema, Rows = tableFile.Data });
    }

    Console.WriteLine($"Loaded {manifest.Tables.Count} tables. Type SQL or a dot-command.");
    Console.WriteLine("  .tables          List all tables");
    Console.WriteLine("  .schema TABLE    Show column definitions");
    Console.WriteLine("  .save            Save all tables back to JSON");
    Console.WriteLine("  .quit / .exit    Quit (prompts to save if unsaved changes)");
    Console.WriteLine();

    bool dirty = false;

    while (true)
    {
        Console.Write("fiesta> ");
        var line = Console.ReadLine();
        if (line == null) break; // EOF
        line = line.Trim();
        if (line == "") continue;

        // Dot-commands
        if (line.StartsWith('.'))
        {
            var parts = line.Split(' ', 2, StringSplitOptions.RemoveEmptyEntries);
            var cmd = parts[0].ToLowerInvariant();

            switch (cmd)
            {
                case ".quit" or ".exit":
                    if (dirty)
                    {
                        Console.Write("Unsaved changes. Save before quitting? [y/N] ");
                        var answer = Console.ReadLine()?.Trim().ToLowerInvariant();
                        if (answer == "y" || answer == "yes")
                            await SaveAllTables(engine, projectService, manifest, tableHeaders, tableSchemas, tableRowEnvironments, project.FullName);
                    }
                    return;

                case ".tables":
                    var tables = engine.ListTables();
                    foreach (var t in tables)
                        Console.WriteLine($"  {t}");
                    Console.WriteLine($"({tables.Count} tables)");
                    break;

                case ".schema" when parts.Length > 1:
                    var tblName = parts[1];
                    if (tableSchemas.TryGetValue(tblName, out var sch))
                    {
                        TableKeyInfo? tblInfo = null;
                        definitions.Tables?.TryGetValue(tblName, out tblInfo);
                        var annotations = tblInfo?.ColumnAnnotations;

                        Console.WriteLine($"-- {tblName} ({sch.SourceFormat})");
                        if (tblInfo?.IdColumn != null) Console.WriteLine($"-- PK: {tblInfo.IdColumn}");
                        if (tblInfo?.KeyColumn != null) Console.WriteLine($"-- Key: {tblInfo.KeyColumn}");

                        foreach (var col in sch.Columns)
                        {
                            var colLine = $"  [{col.Name}] {col.Type} (len={col.Length}, shn={col.SourceTypeCode})";
                            if (annotations?.TryGetValue(col.Name, out var ann) == true)
                            {
                                if (ann.DisplayName != null) colLine += $"  -- {ann.DisplayName}";
                                if (ann.Description != null) colLine += $": {ann.Description}";
                            }
                            Console.WriteLine(colLine);
                        }
                    }
                    else
                        Console.WriteLine($"Unknown table: {tblName}");
                    break;

                case ".save":
                    await SaveAllTables(engine, projectService, manifest, tableHeaders, tableSchemas, tableRowEnvironments, project.FullName);
                    dirty = false;
                    break;

                case ".help":
                    Console.WriteLine("  .tables          List all tables");
                    Console.WriteLine("  .schema TABLE    Show column definitions");
                    Console.WriteLine("  .save            Save all tables back to JSON");
                    Console.WriteLine("  .quit / .exit    Quit (prompts to save if unsaved changes)");
                    break;

                default:
                    Console.WriteLine($"Unknown command: {cmd}");
                    break;
            }
            continue;
        }

        // SQL
        try
        {
            var upper = line.TrimStart().ToUpperInvariant();
            if (upper.StartsWith("SELECT") || upper.StartsWith("PRAGMA") || upper.StartsWith("EXPLAIN"))
            {
                var results = engine.Query(line);
                if (results.Count > 0)
                {
                    // Print header
                    var cols = results[0].Keys.ToList();
                    Console.WriteLine(string.Join(" | ", cols));
                    Console.WriteLine(new string('-', cols.Sum(c => c.Length + 3)));
                    foreach (var row in results)
                    {
                        Console.WriteLine(string.Join(" | ", cols.Select(c => row[c]?.ToString() ?? "NULL")));
                    }
                }
                Console.WriteLine($"({results.Count} rows)");
            }
            else
            {
                var affected = engine.Execute(line);
                Console.WriteLine($"{affected} rows affected");
                if (affected > 0) dirty = true;
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }

}, shellProjectOpt);

// --- init-template command ---
var initTemplateCommand = new Command("init-template", "Auto-generate a fiesta.template.json from environment scans");
var initTemplateProjectOpt = MakeProjectOption();
var initTemplatePassthroughOption = new Option<string[]>("--passthrough",
    "Copy all non-table files from the named environment(s) to build output (e.g. --passthrough server)")
{
    AllowMultipleArgumentsPerToken = false,
    Arity = ArgumentArity.ZeroOrMore
};
initTemplateCommand.AddOption(initTemplateProjectOpt);
initTemplateCommand.AddOption(initTemplatePassthroughOption);

initTemplateCommand.SetHandler(async (DirectoryInfo? projectOpt, string[] passthroughEnvs) =>
{
    var logger = sp.GetRequiredService<ILogger<Program>>();
    var project = ResolveProjectOrExit(projectOpt, logger);
    var projectService = sp.GetRequiredService<IProjectService>();
    var providers = sp.GetServices<IDataProvider>().ToList();

    var manifest = await projectService.LoadProjectAsync(project.FullName);

    var allEnvs = EnvironmentStore.LoadAll(project.FullName);
    if (allEnvs.Count == 0)
    {
        logger.LogError("No environments configured. Use: fiesta env <name> init <importPath>");
        return;
    }

    // Scan each environment
    var envTables = new Dictionary<(string table, string env), TableFile>();
    var envOrder = allEnvs.Keys.ToList();

    foreach (var (envName, envConfig) in allEnvs)
    {
        if (envConfig.ImportPath == null) { logger.LogWarning("Skipping {Env}: import-path not set.", envName); continue; }
        var sourceDir = new DirectoryInfo(envConfig.ImportPath);
        if (!sourceDir.Exists)
        {
            logger.LogWarning("Import path does not exist for environment {Env}: {Path}", envName, envConfig.ImportPath);
            continue;
        }

        logger.LogInformation("Scanning {Env}: {Path}", envName, sourceDir.FullName);
        var tables = await ReadAllTables(sourceDir, providers, logger);

        foreach (var (tableName, (tableFile, _)) in tables)
            envTables[(tableName, envName)] = tableFile;

        logger.LogInformation("Found {Count} tables in {Env}", tables.Count, envName);
    }

    // Detect passthrough files: envs with Passthrough=true in config, plus any explicit --passthrough flags.
    var passthroughFiles = new List<(string env, string path)>();
    var passthroughEnvSet = allEnvs
        .Where(kvp => kvp.Value.Passthrough)
        .Select(kvp => kvp.Key)
        .Concat(passthroughEnvs)
        .ToHashSet(StringComparer.OrdinalIgnoreCase);

    foreach (var (envName, envConfig) in allEnvs)
    {
        if (!passthroughEnvSet.Contains(envName)) continue;
        if (envConfig.ImportPath == null) continue;
        var sourceDir = new DirectoryInfo(envConfig.ImportPath);
        if (!sourceDir.Exists) continue;

        foreach (var file in sourceDir.EnumerateFiles("*", SearchOption.AllDirectories))
        {
            if (providers.Any(p => p.CanHandle(file.FullName))) continue;

            var relPath = Path.GetRelativePath(sourceDir.FullName, file.FullName).Replace('\\', '/');
            passthroughFiles.Add((envName, relPath));
        }
    }

    var template = TemplateGenerator.Generate(envTables, envOrder, passthroughFiles);
    await TemplateResolver.SaveAsync(project.FullName, template);

    var copyCount = template.Actions.Count(a => a.Action == "copy");
    var mergeCount = template.Actions.Count(a => a.Action == "merge");
    var pkCount = template.Actions.Count(a => a.Action == "setPrimaryKey");
    var ukCount = template.Actions.Count(a => a.Action == "setUniqueKey");
    var copyFileCount = template.Actions.Count(a => a.Action == "copyFile");

    logger.LogInformation("Generated {File} with {Actions} actions: {Copy} copy, {Merge} merge, {PK} setPK, {UK} setUK, {CopyFile} copyFile",
        TemplateResolver.TemplateFileName, template.Actions.Count, copyCount, mergeCount, pkCount, ukCount, copyFileCount);

}, initTemplateProjectOpt, initTemplatePassthroughOption);

// --- edit-template command ---
var editTemplateCommand = new Command("edit-template", "Modify merge actions in fiesta.template.json");
var editTemplateProjectOpt = MakeProjectOption();
var editTemplateTableOption = new Option<string?>("--table", "Target a specific table (applies to all merge actions if omitted)");
editTemplateTableOption.AddAlias("-t");
var conflictStrategyOption = new Option<string?>("--conflict-strategy", "Set conflict strategy on merge actions (report or split)");
editTemplateCommand.AddOption(editTemplateProjectOpt);
editTemplateCommand.AddOption(editTemplateTableOption);
editTemplateCommand.AddOption(conflictStrategyOption);

editTemplateCommand.SetHandler(async (DirectoryInfo? projectOpt, string? table, string? conflictStrategyVal) =>
{
    var logger = sp.GetRequiredService<ILogger<Program>>();
    var project = ResolveProjectOrExit(projectOpt, logger);

    var templatePath = Path.Combine(project.FullName, TemplateResolver.TemplateFileName);
    if (!File.Exists(templatePath))
    {
        logger.LogError("No {File} found in {Dir}. Run init-template first.", TemplateResolver.TemplateFileName, project.FullName);
        return;
    }

    var json = await File.ReadAllTextAsync(templatePath);
    var doc = System.Text.Json.Nodes.JsonNode.Parse(json)!.AsObject();
    var actions = doc["actions"]!.AsArray();

    int modified = 0;
    foreach (var action in actions)
    {
        var obj = action!.AsObject();
        if (obj["action"]?.GetValue<string>() != "merge") continue;
        if (table != null && obj["into"]?.GetValue<string>() != table) continue;

        if (conflictStrategyVal != null)
        {
            obj["conflictStrategy"] = conflictStrategyVal;
            modified++;
        }
    }

    if (modified == 0)
    {
        logger.LogWarning("No merge actions matched{Table}.", table != null ? $" for table {table}" : "");
        return;
    }

    var writeOptions = new System.Text.Json.JsonSerializerOptions { WriteIndented = true };
    await File.WriteAllTextAsync(templatePath, doc.ToJsonString(writeOptions));
    logger.LogInformation("Updated {Count} merge action(s) in {File}", modified, TemplateResolver.TemplateFileName);

}, editTemplateProjectOpt, editTemplateTableOption, conflictStrategyOption);

// --- shn command ---
var shnCommand = new Command("shn", "Inspect SHN binary files without a project");
var shnFileArg = new Argument<FileInfo>("file", "SHN file to inspect");
var shnSchemaOpt = new Option<bool>("--schema", "Print column schema (default when no other mode given)");
var shnRowCountOpt = new Option<bool>("--row-count", "Print record count only");
var shnHeadOpt = new Option<int?>("--head", "Print first N rows");
var shnTailOpt = new Option<int?>("--tail", "Print last N rows");
var shnSkipOpt = new Option<int>("--skip", () => 0, "Skip first N rows (combine with --head/--take)");
var shnTakeOpt = new Option<int?>("--take", "Print N rows starting after --skip");
var shnDiffOpt = new Option<FileInfo?>("--diff", "Compare against a second SHN file (positional row diff)");
var shnDecryptOpt = new Option<FileInfo?>("--decrypt-to", "Write decrypted raw bytes to this file");
var shnMaxDiffsOpt = new Option<int>("--max-diffs", () => 20, "Max differing rows to display (default: 20)");
shnCommand.AddArgument(shnFileArg);
shnCommand.AddOption(shnSchemaOpt);
shnCommand.AddOption(shnRowCountOpt);
shnCommand.AddOption(shnHeadOpt);
shnCommand.AddOption(shnTailOpt);
shnCommand.AddOption(shnSkipOpt);
shnCommand.AddOption(shnTakeOpt);
shnCommand.AddOption(shnDiffOpt);
shnCommand.AddOption(shnDecryptOpt);
shnCommand.AddOption(shnMaxDiffsOpt);

shnCommand.SetHandler(context =>
{
    var file      = context.ParseResult.GetValueForArgument(shnFileArg);
    var schema    = context.ParseResult.GetValueForOption(shnSchemaOpt);
    var rowCount  = context.ParseResult.GetValueForOption(shnRowCountOpt);
    var head      = context.ParseResult.GetValueForOption(shnHeadOpt);
    var tail      = context.ParseResult.GetValueForOption(shnTailOpt);
    var skip      = context.ParseResult.GetValueForOption(shnSkipOpt);
    var take      = context.ParseResult.GetValueForOption(shnTakeOpt);
    var diff      = context.ParseResult.GetValueForOption(shnDiffOpt);
    var decryptTo = context.ParseResult.GetValueForOption(shnDecryptOpt);
    var maxDiffs  = context.ParseResult.GetValueForOption(shnMaxDiffsOpt);

    if (!file.Exists)
    {
        Console.Error.WriteLine($"error: file not found: {file.FullName}");
        return;
    }

    // --decrypt-to: standalone mode
    if (decryptTo != null)
    {
        Fiesta.Collab.Cli.ShnInspectCommand.Decrypt(file.FullName, decryptTo.FullName);
        return;
    }

    // --diff: standalone mode
    if (diff != null)
    {
        if (!diff.Exists)
        {
            Console.Error.WriteLine($"error: file not found: {diff.FullName}");
            return;
        }
        Fiesta.Collab.Cli.ShnInspectCommand.Diff(file.FullName, diff.FullName, maxDiffs);
        return;
    }

    // --row-count only: just print the number
    if (rowCount && !schema && !head.HasValue && !tail.HasValue && !take.HasValue && skip == 0)
    {
        Fiesta.Collab.Cli.ShnInspectCommand.PrintRowCount(file.FullName);
        return;
    }

    // Row display modes
    bool rowMode    = head.HasValue || tail.HasValue || take.HasValue || skip > 0;
    bool schemaMode = schema || rowCount || !rowMode; // default to schema when nothing else set

    if (schemaMode)
        Fiesta.Collab.Cli.ShnInspectCommand.PrintSchema(file.FullName);

    if (rowMode)
    {
        if (schemaMode) Console.WriteLine();
        Fiesta.Collab.Cli.ShnInspectCommand.PrintRows(file.FullName, skip, take, head, tail);
    }
});



// --- env command ---
var envCommand = new Command("env", "Manage project environments (environments/<name>.json)");
var envProjectOption = MakeProjectOption();
var envArgsArg = new Argument<string[]>("args", "env <name|all> <verb> [args...]")
{
    Arity = ArgumentArity.ZeroOrMore
};
envCommand.AddOption(envProjectOption);
envCommand.AddArgument(envArgsArg);
envCommand.SetHandler(async (DirectoryInfo? projectOpt, string[] tokens) =>
{
    var logger = sp.GetRequiredService<ILogger<Program>>();
    var project = ResolveProjectOrExit(projectOpt, logger);
    await Fiesta.Collab.Cli.EnvCommand.HandleAsync(project.FullName, tokens, logger);
}, envProjectOption, envArgsArg);

rootCommand.AddCommand(envCommand);
rootCommand.AddCommand(initCommand);
rootCommand.AddCommand(importCommand);
rootCommand.AddCommand(reimportCommand);
rootCommand.AddCommand(buildCommand);
rootCommand.AddCommand(queryCommand);
rootCommand.AddCommand(editCommand);
rootCommand.AddCommand(shellCommand);
rootCommand.AddCommand(validateCommand);
rootCommand.AddCommand(initTemplateCommand);
rootCommand.AddCommand(editTemplateCommand);
rootCommand.AddCommand(shnCommand);
rootCommand.AddCommand(dumpCommand);
rootCommand.AddCommand(analyzeCommand);

return await rootCommand.InvokeAsync(args);

// --- import helper ---

async Task<Dictionary<string, (TableFile file, string relDir)>> ReadAllTables(
    DirectoryInfo sourceDir, List<IDataProvider> providers, ILogger logger)
{
    // Pass 1: collect all entries with their source paths
    var allEntries = new List<(string sourceName, string relDir, TableFile tableFile)>();

    foreach (var file in sourceDir.EnumerateFiles("*", SearchOption.AllDirectories))
    {
        var provider = providers.FirstOrDefault(p => p.CanHandle(file.FullName));
        if (provider is null) continue;

        try
        {
            var entries = await provider.ReadAsync(file.FullName);
            var relDir = Path.GetDirectoryName(
                Path.GetRelativePath(sourceDir.FullName, file.FullName))?.Replace('\\', '/') ?? "";

            foreach (var entry in entries)
            {
                allEntries.Add((entry.Schema.TableName, relDir, new TableFile
                {
                    Header = new TableHeader
                    {
                        TableName = entry.Schema.TableName,
                        SourceFormat = entry.Schema.SourceFormat,
                        Metadata = entry.Schema.Metadata
                    },
                    Columns = entry.Schema.Columns,
                    Data = entry.Rows
                }));
            }
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Failed to read {File}", file.Name);
        }
    }

    // Pass 2: assign unique internal names — same-source-name files at different paths
    // get a namespace prefix derived from the extra path components (e.g. "View.ActionViewInfo").
    // The shallower (fewer path separators) occurrence keeps the original name.
    var result = new Dictionary<string, (TableFile file, string relDir)>();

    foreach (var group in allEntries.GroupBy(e => e.sourceName))
    {
        var ordered = group
            .OrderBy(e => e.relDir.Count(c => c == '/'))
            .ThenBy(e => e.relDir)
            .ToList();

        for (int i = 0; i < ordered.Count; i++)
        {
            var (sourceName, relDir, tableFile) = ordered[i];
            string internalName;

            if (i == 0)
            {
                internalName = sourceName;
            }
            else
            {
                var primaryRelDir = ordered[0].relDir;
                var primaryParts = primaryRelDir.Split('/', StringSplitOptions.RemoveEmptyEntries);
                var deeperParts = relDir.Split('/', StringSplitOptions.RemoveEmptyEntries);
                var extraParts = deeperParts.Length > primaryParts.Length
                    ? deeperParts.Skip(primaryParts.Length).ToArray()
                    : new[] { deeperParts.LastOrDefault() ?? "dup" };
                var prefix = string.Join(".", extraParts);
                internalName = $"{prefix}.{sourceName}";
                logger.LogWarning(
                    "Same table name '{Name}' at multiple paths in env. '{Primary}' is primary; '{Rel}' mapped to internal name '{Internal}'",
                    sourceName, ordered[0].relDir, relDir, internalName);
            }

            result[internalName] = (tableFile, relDir);
        }
    }

    return result;
}

// --- shared helpers ---

async Task LoadTablesWithConstraints(
    ISqlEngine engine, IProjectService projectService, FiestaProject manifest,
    string projectDir, ILogger logger)
{
    // Load constraints from template (preferred) or definitions file (legacy)
    var definitions = await LoadDefinitions(projectDir, logger);
    var resolved = DefinitionResolver.Resolve(definitions, manifest);

    if (resolved.Count > 0 || definitions.Tables?.Count > 0)
    {
        engine.SetConstraints(resolved, definitions.Tables);
        logger.LogInformation("Registered {Count} FK constraints, {KeyCount} table keys",
            resolved.Count, definitions.Tables?.Count ?? 0);
    }

    // Determine load order (referenced tables first)
    var loadOrder = engine.GetLoadOrder(manifest.Tables.Keys);

    foreach (var tableName in loadOrder)
    {
        var entryPath = manifest.Tables[tableName];
        var tableFile = await projectService.ReadTableFileAsync(projectDir, entryPath);

        var entry = new TableEntry
        {
            Schema = new TableSchema
            {
                TableName = tableName,  // use manifest key — header TableName may collide across envs
                SourceFormat = tableFile.Header.SourceFormat,
                Columns = tableFile.Columns,
                Metadata = tableFile.Header.Metadata
            },
            Rows = tableFile.Data
        };
        engine.LoadTable(entry);
    }

    if (resolved.Count > 0 || definitions.Tables?.Count > 0)
        engine.EnableForeignKeys();

    logger.LogInformation("Loaded {Count} tables into SQLite", manifest.Tables.Count);
}

async Task<ProjectDefinitions> LoadDefinitions(string projectDir, ILogger logger)
{
    // Prefer template if it exists
    var template = await TemplateResolver.LoadAsync(projectDir);
    if (template.Actions.Count > 0)
    {
        logger.LogDebug("Using template for constraints/keys");
        return TemplateDefinitionBridge.ToDefinitions(template);
    }

    // Fall back to legacy definitions file
    return await DefinitionResolver.LoadAsync(projectDir);
}

async Task SaveAllTables(
    ISqlEngine engine, IProjectService projectService, FiestaProject manifest,
    Dictionary<string, TableHeader> headers, Dictionary<string, TableSchema> schemas,
    Dictionary<string, IReadOnlyList<List<string>?>?> rowEnvironments,
    string projectDir)
{
    int saved = 0;
    foreach (var (name, entryPath) in manifest.Tables)
    {
        var schema = schemas[name];
        var extracted = engine.ExtractTable(schema);

        var tableFile = new TableFile
        {
            Header = headers[name],
            Columns = schema.Columns,
            Data = extracted.Rows,
            RowEnvironments = rowEnvironments.GetValueOrDefault(name)
        };

        await projectService.WriteTableFileAsync(projectDir, entryPath, tableFile);
        saved++;
    }
    Console.WriteLine($"Saved {saved} tables.");
}

static int GetSectionIndex(IDictionary<string, object>? metadata)
{
    if (metadata?.TryGetValue("sectionIndex", out var val) != true) return int.MaxValue;
    return val switch
    {
        int i => i,
        long l => (int)l,
        System.Text.Json.JsonElement je when je.ValueKind == System.Text.Json.JsonValueKind.Number => je.GetInt32(),
        _ => int.TryParse(val?.ToString(), out int parsed) ? parsed : int.MaxValue
    };
}

// --- project discovery (git-like CWD detection) ---

static string? FindProjectRoot()
{
    var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
    while (dir != null)
    {
        if (File.Exists(Path.Combine(dir.FullName, "fiesta.json")))
            return dir.FullName;
        dir = dir.Parent;
    }
    return null;
}

static DirectoryInfo ResolveProjectOrExit(DirectoryInfo? provided, ILogger logger)
{
    if (provided != null) return provided;

    var found = FindProjectRoot();
    if (found != null)
    {
        logger.LogDebug("Using project at {Dir} (discovered from CWD)", found);
        return new DirectoryInfo(found);
    }

    Console.Error.WriteLine("error: not a fiesta project (or any parent up to root: fiesta.json not found)");
    Console.Error.WriteLine("hint: create a project with 'fiesta init <name> --env server=<path>'");
    Environment.Exit(1);
    return null!; // unreachable
}
